//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 03 23:49:22 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GoUnity_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface OnApplicationQuit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static OnApplicationQuit As<T>(in T target) => (OnApplicationQuit<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static OnApplicationQuit As<T>(ptr<T> target_ptr) => (OnApplicationQuit<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static OnApplicationQuit? As(object target) =>
                typeof(OnApplicationQuit<>).CreateInterfaceHandler<OnApplicationQuit>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class OnApplicationQuit<T> : OnApplicationQuit
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public OnApplicationQuit(in T target) => m_target = target;

            public OnApplicationQuit(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void OnApplicationQuitByPtr(ptr<T> value);
            private delegate void OnApplicationQuitByVal(T value);

            private static readonly OnApplicationQuitByPtr? s_OnApplicationQuitByPtr;
            private static readonly OnApplicationQuitByVal? s_OnApplicationQuitByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void OnApplicationQuit()
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s_OnApplicationQuitByPtr is null || !m_target_is_ptr)
                {
                    s_OnApplicationQuitByVal!(target);
                    return;
                }

                s_OnApplicationQuitByPtr(m_target_ptr);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static OnApplicationQuit()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("OnApplicationQuit");

                if (!(extensionMethod is null))
                    s_OnApplicationQuitByPtr = extensionMethod.CreateStaticDelegate(typeof(OnApplicationQuitByPtr)) as OnApplicationQuitByPtr;

                extensionMethod = targetType.GetExtensionMethod("OnApplicationQuit");

                if (!(extensionMethod is null))
                    s_OnApplicationQuitByVal = extensionMethod.CreateStaticDelegate(typeof(OnApplicationQuitByVal)) as OnApplicationQuitByVal;

                if (s_OnApplicationQuitByPtr is null && s_OnApplicationQuitByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement OnApplicationQuit.OnApplicationQuit method", new Exception("OnApplicationQuit"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator OnApplicationQuit<T>(in ptr<T> target_ptr) => new OnApplicationQuit<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator OnApplicationQuit<T>(in T target) => new OnApplicationQuit<T>(target);

            // Enable comparisons between nil and OnApplicationQuit<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(OnApplicationQuit<T> value, NilType nil) => Activator.CreateInstance<OnApplicationQuit<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(OnApplicationQuit<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, OnApplicationQuit<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, OnApplicationQuit<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GoUnity_OnApplicationQuitExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GoUnity_package.OnApplicationQuit target)
        {
            try
            {
                return ((go.GoUnity_package.OnApplicationQuit<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GoUnity_package.OnApplicationQuit target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GoUnity_package.OnApplicationQuit target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GoUnity_package.OnApplicationQuit<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GoUnity_package.OnApplicationQuit target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}