//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 04 10:02:34 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GoUnity_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IOnCollisionEnter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IOnCollisionEnter As<T>(in T target) => (IOnCollisionEnter<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IOnCollisionEnter As<T>(ptr<T> target_ptr) => (IOnCollisionEnter<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IOnCollisionEnter? As(object target) =>
                typeof(IOnCollisionEnter<>).CreateInterfaceHandler<IOnCollisionEnter>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IOnCollisionEnter<T> : IOnCollisionEnter
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IOnCollisionEnter(in T target) => m_target = target;

            public IOnCollisionEnter(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void OnCollisionEnterByPtr(ptr<T> value, Collision other);
            private delegate void OnCollisionEnterByVal(T value, Collision other);

            private static readonly OnCollisionEnterByPtr? s_OnCollisionEnterByPtr;
            private static readonly OnCollisionEnterByVal? s_OnCollisionEnterByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void OnCollisionEnter(Collision other)
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s_OnCollisionEnterByPtr is null || !m_target_is_ptr)
                {
                    s_OnCollisionEnterByVal!(target, other);
                    return;
                }

                s_OnCollisionEnterByPtr(m_target_ptr, other);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IOnCollisionEnter()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("OnCollisionEnter");

                if (!(extensionMethod is null))
                    s_OnCollisionEnterByPtr = extensionMethod.CreateStaticDelegate(typeof(OnCollisionEnterByPtr)) as OnCollisionEnterByPtr;

                extensionMethod = targetType.GetExtensionMethod("OnCollisionEnter");

                if (!(extensionMethod is null))
                    s_OnCollisionEnterByVal = extensionMethod.CreateStaticDelegate(typeof(OnCollisionEnterByVal)) as OnCollisionEnterByVal;

                if (s_OnCollisionEnterByPtr is null && s_OnCollisionEnterByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IOnCollisionEnter.OnCollisionEnter method", new Exception("OnCollisionEnter"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IOnCollisionEnter<T>(in ptr<T> target_ptr) => new IOnCollisionEnter<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IOnCollisionEnter<T>(in T target) => new IOnCollisionEnter<T>(target);

            // Enable comparisons between nil and IOnCollisionEnter<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IOnCollisionEnter<T> value, NilType nil) => Activator.CreateInstance<IOnCollisionEnter<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IOnCollisionEnter<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IOnCollisionEnter<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IOnCollisionEnter<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GoUnity_IOnCollisionEnterExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GoUnity_package.IOnCollisionEnter target)
        {
            try
            {
                return ((go.GoUnity_package.IOnCollisionEnter<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GoUnity_package.IOnCollisionEnter target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GoUnity_package.IOnCollisionEnter target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GoUnity_package.IOnCollisionEnter<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GoUnity_package.IOnCollisionEnter target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}