//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 03 23:49:22 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GoUnity_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface OnApplicationFocus
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static OnApplicationFocus As<T>(in T target) => (OnApplicationFocus<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static OnApplicationFocus As<T>(ptr<T> target_ptr) => (OnApplicationFocus<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static OnApplicationFocus? As(object target) =>
                typeof(OnApplicationFocus<>).CreateInterfaceHandler<OnApplicationFocus>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class OnApplicationFocus<T> : OnApplicationFocus
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public OnApplicationFocus(in T target) => m_target = target;

            public OnApplicationFocus(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void OnApplicationFocusByPtr(ptr<T> value, bool hasFocus);
            private delegate void OnApplicationFocusByVal(T value, bool hasFocus);

            private static readonly OnApplicationFocusByPtr? s_OnApplicationFocusByPtr;
            private static readonly OnApplicationFocusByVal? s_OnApplicationFocusByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void OnApplicationFocus(bool hasFocus)
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s_OnApplicationFocusByPtr is null || !m_target_is_ptr)
                {
                    s_OnApplicationFocusByVal!(target, hasFocus);
                    return;
                }

                s_OnApplicationFocusByPtr(m_target_ptr, hasFocus);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static OnApplicationFocus()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("OnApplicationFocus");

                if (!(extensionMethod is null))
                    s_OnApplicationFocusByPtr = extensionMethod.CreateStaticDelegate(typeof(OnApplicationFocusByPtr)) as OnApplicationFocusByPtr;

                extensionMethod = targetType.GetExtensionMethod("OnApplicationFocus");

                if (!(extensionMethod is null))
                    s_OnApplicationFocusByVal = extensionMethod.CreateStaticDelegate(typeof(OnApplicationFocusByVal)) as OnApplicationFocusByVal;

                if (s_OnApplicationFocusByPtr is null && s_OnApplicationFocusByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement OnApplicationFocus.OnApplicationFocus method", new Exception("OnApplicationFocus"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator OnApplicationFocus<T>(in ptr<T> target_ptr) => new OnApplicationFocus<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator OnApplicationFocus<T>(in T target) => new OnApplicationFocus<T>(target);

            // Enable comparisons between nil and OnApplicationFocus<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(OnApplicationFocus<T> value, NilType nil) => Activator.CreateInstance<OnApplicationFocus<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(OnApplicationFocus<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, OnApplicationFocus<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, OnApplicationFocus<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GoUnity_OnApplicationFocusExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GoUnity_package.OnApplicationFocus target)
        {
            try
            {
                return ((go.GoUnity_package.OnApplicationFocus<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GoUnity_package.OnApplicationFocus target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GoUnity_package.OnApplicationFocus target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GoUnity_package.OnApplicationFocus<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GoUnity_package.OnApplicationFocus target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}