//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 04 10:02:34 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GoUnity_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IOnAnimatorIK
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IOnAnimatorIK As<T>(in T target) => (IOnAnimatorIK<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IOnAnimatorIK As<T>(ptr<T> target_ptr) => (IOnAnimatorIK<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IOnAnimatorIK? As(object target) =>
                typeof(IOnAnimatorIK<>).CreateInterfaceHandler<IOnAnimatorIK>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IOnAnimatorIK<T> : IOnAnimatorIK
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IOnAnimatorIK(in T target) => m_target = target;

            public IOnAnimatorIK(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void OnAnimatorIKByPtr(ptr<T> value, nint layerIndex);
            private delegate void OnAnimatorIKByVal(T value, nint layerIndex);

            private static readonly OnAnimatorIKByPtr? s_OnAnimatorIKByPtr;
            private static readonly OnAnimatorIKByVal? s_OnAnimatorIKByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void OnAnimatorIK(nint layerIndex)
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s_OnAnimatorIKByPtr is null || !m_target_is_ptr)
                {
                    s_OnAnimatorIKByVal!(target, layerIndex);
                    return;
                }

                s_OnAnimatorIKByPtr(m_target_ptr, layerIndex);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IOnAnimatorIK()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("OnAnimatorIK");

                if (!(extensionMethod is null))
                    s_OnAnimatorIKByPtr = extensionMethod.CreateStaticDelegate(typeof(OnAnimatorIKByPtr)) as OnAnimatorIKByPtr;

                extensionMethod = targetType.GetExtensionMethod("OnAnimatorIK");

                if (!(extensionMethod is null))
                    s_OnAnimatorIKByVal = extensionMethod.CreateStaticDelegate(typeof(OnAnimatorIKByVal)) as OnAnimatorIKByVal;

                if (s_OnAnimatorIKByPtr is null && s_OnAnimatorIKByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IOnAnimatorIK.OnAnimatorIK method", new Exception("OnAnimatorIK"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IOnAnimatorIK<T>(in ptr<T> target_ptr) => new IOnAnimatorIK<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IOnAnimatorIK<T>(in T target) => new IOnAnimatorIK<T>(target);

            // Enable comparisons between nil and IOnAnimatorIK<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IOnAnimatorIK<T> value, NilType nil) => Activator.CreateInstance<IOnAnimatorIK<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IOnAnimatorIK<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IOnAnimatorIK<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IOnAnimatorIK<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GoUnity_IOnAnimatorIKExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GoUnity_package.IOnAnimatorIK target)
        {
            try
            {
                return ((go.GoUnity_package.IOnAnimatorIK<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GoUnity_package.IOnAnimatorIK target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GoUnity_package.IOnAnimatorIK target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GoUnity_package.IOnAnimatorIK<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GoUnity_package.IOnAnimatorIK target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}