//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 03 23:49:24 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;

#nullable enable

namespace go
{
    public static partial class GoUnity_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct SplineFollow3D
        {
            // Constructors
            public SplineFollow3D(NilType _)
            {
                this.Segments = default;
                this.DoLoop = default;
                this.Cube = default;
                this.Speed = default;
            }

            public SplineFollow3D(nint Segments = default, bool DoLoop = default, Transform Cube = default, float Speed = default)
            {
                this.Segments = Segments;
                this.DoLoop = DoLoop;
                this.Cube = Cube;
                this.Speed = Speed;
            }

            // Enable comparisons between nil and SplineFollow3D struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(SplineFollow3D value, NilType nil) => value.Equals(default(SplineFollow3D));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(SplineFollow3D value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, SplineFollow3D value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, SplineFollow3D value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator SplineFollow3D(NilType nil) => default(SplineFollow3D);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static SplineFollow3D SplineFollow3D_cast(dynamic value)
        {
            return new SplineFollow3D(value.Segments, value.DoLoop, value.Cube, value.Speed);
        }
    }
}